#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# Nexus Social — One-Command Setup Script
#
# What this does:
#   1. Logs you into Turso (opens browser once)
#   2. Creates the nexus-social database on Turso
#   3. Generates an auth token
#   4. Writes your .env file automatically
#   5. Pushes the database schema to Turso
#   6. Builds the app
#   7. Starts the production server
#
# Run it:
#   chmod +x setup.sh
#   ./setup.sh
# ─────────────────────────────────────────────────────────────────────────────

set -e  # Stop on any error

TURSO=/home/user/.turso/turso
PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$PROJECT_DIR/.env"
DB_NAME="nexus-social"

echo ""
echo "╔══════════════════════════════════════════════════════╗"
echo "║          Nexus Social — Setup Script                 ║"
echo "╚══════════════════════════════════════════════════════╝"
echo ""

# ── Step 1: Turso login ───────────────────────────────────────────────────────
echo "▶  Step 1/6 — Logging into Turso..."
echo "   This will open your browser. Sign up or log in, then come back here."
echo ""
$TURSO auth login
echo ""
echo "✅  Logged in."
echo ""

# ── Step 2: Create database ───────────────────────────────────────────────────
echo "▶  Step 2/6 — Creating database '$DB_NAME' on Turso..."
# Create only if it doesn't exist yet
if $TURSO db show "$DB_NAME" &>/dev/null; then
  echo "   Database '$DB_NAME' already exists — skipping create."
else
  $TURSO db create "$DB_NAME"
  echo "✅  Database created."
fi
echo ""

# ── Step 3: Get URL and token ─────────────────────────────────────────────────
echo "▶  Step 3/6 — Fetching credentials..."
DB_URL=$($TURSO db show "$DB_NAME" --url)
DB_TOKEN=$($TURSO db tokens create "$DB_NAME")
echo "   URL:   $DB_URL"
echo "   Token: ${DB_TOKEN:0:20}..."
echo ""

# ── Step 4: Write .env ────────────────────────────────────────────────────────
echo "▶  Step 4/6 — Writing .env file..."

# Generate a random ADMIN_SECRET
ADMIN_SECRET=$(openssl rand -hex 24 2>/dev/null || cat /dev/urandom | tr -dc 'a-zA-Z0-9' | head -c 48)

cat > "$ENV_FILE" <<EOF
# Nexus Social — Environment Variables
# Generated by setup.sh on $(date)
# DO NOT COMMIT THIS FILE

# Turso (cloud database)
TURSO_DATABASE_URL=$DB_URL
TURSO_AUTH_TOKEN=$DB_TOKEN

# Security audit log — keep this secret
ADMIN_SECRET=$ADMIN_SECRET

# Server
NODE_ENV=production
PORT=5000
EOF

echo "✅  .env written to: $ENV_FILE"
echo ""

# ── Step 5: Push schema to Turso ─────────────────────────────────────────────
echo "▶  Step 5/6 — Installing dependencies and pushing schema..."
cd "$PROJECT_DIR"
npm install --silent

# Load env vars for drizzle-kit
export TURSO_DATABASE_URL="$DB_URL"
export TURSO_AUTH_TOKEN="$DB_TOKEN"
export NODE_ENV=production

# The app auto-creates tables on startup via initTables() in storage.ts,
# so we just do a quick connection test here.
node -e "
const { createClient } = require('@libsql/client');
const c = createClient({ url: '$DB_URL', authToken: '$DB_TOKEN' });
c.execute('SELECT 1').then(() => {
  console.log('   Database connection: OK');
  process.exit(0);
}).catch(e => {
  console.error('   Database connection FAILED:', e.message);
  process.exit(1);
});
" 2>/dev/null || node --input-type=module <<'NODEEOF'
import { createClient } from '@libsql/client';
const c = createClient({ url: process.env.TURSO_DATABASE_URL, authToken: process.env.TURSO_AUTH_TOKEN });
try { await c.execute('SELECT 1'); console.log('   Database connection: OK'); }
catch(e) { console.error('   FAILED:', e.message); process.exit(1); }
NODEEOF

echo ""

# ── Step 6: Build ─────────────────────────────────────────────────────────────
echo "▶  Step 6/6 — Building the app..."
npm run build
echo "✅  Build complete."
echo ""

# ── Done ──────────────────────────────────────────────────────────────────────
echo "╔══════════════════════════════════════════════════════╗"
echo "║  ✅  Setup complete!                                  ║"
echo "╚══════════════════════════════════════════════════════╝"
echo ""
echo "  Your credentials are saved in: .env"
echo "  Your ADMIN_SECRET is:          $ADMIN_SECRET"
echo ""
echo "  To start the server:"
echo "    NODE_ENV=production node dist/index.cjs"
echo ""
echo "  To read the security audit log:"
echo "    curl http://localhost:5000/api/admin/security-events \\"
echo "      -H \"X-Admin-Secret: $ADMIN_SECRET\""
echo ""
